### ISSUE TITLE
Regex with nested group seems to have exponential runtime based on input

### ISSUE THREAD

**Issue by robinst** [google/fancy-regex#14]
With current master (af9f249e0299ef79c514fe2876e86662ee16e481), add the following to `tests/matching.rs`:

```rust
#[test]
fn bad_regex() {
    let regex = Regex::new(r"(?x)
^(?=
  (
    (
      [^|]+(?=[|]|$)
    )+
  )*
  \|
)").unwrap();
    assert_eq!(Some(false), regex.is_match("hi this is a test").ok());
}
```

Running it doesn't finish, killed it after a minute. Oniguruma handles it fine. When using a shorter input text such as `"test"`, it completes, so the runtime is based on the input length.

Experimenting with the regex, the problem seems to be the nested groups that have this pattern: `((a)+)*`. When removing one of those groups, the problem goes away.

A nested group like that doesn't make a lot of sense if it was written in one regex, but it's from a regex that is generated from multiple components here: https://github.com/sublimehq/Packages/blob/66bf9ac00d3cde7296182b84aec2702477c5fc40/Markdown/Markdown.sublime-syntax#L78-L94

**Comment by raphlinus** [comment]
I believe Oniguruma (and most industrial-strength RE engines) optimize these, as a pure backtracking implementation has pathological performance.

If it's just a recognizer, ie you don't care about captures, then the optimization is trivial, `(a+)*` can just be rewritten as `a*`. I _think_ that `(a+)?` is equivalent in all senses (including captures) and efficient; this would be an easy optimization as well (ie to generate code for `*` just check whether the expr being repeated is a repetition).

Anyone care to check these assertions? If valid, I can do the optimization.

**Comment by robinst** [comment]
Captures are an interesting point, yeah. I haven't yet checked what Oniguruma does with captures in that case, will do some experiments tomorrow.

I had a look at the source code and this looks like the place where Oniguruma handles that case:

* [check in `set_quantifier` function](https://github.com/kkos/oniguruma/blob/c4ce370f5754b34321c7f87cdc6f198864221eca/src/regparse.c#L4753)
* [optimization logic in `onig_reduce_nested_quantifier`](https://github.com/kkos/oniguruma/blob/c4ce370f5754b34321c7f87cdc6f198864221eca/src/regparse.c#L2146)

**Comment by robinst** [comment]
So I tested that Oniguruma handles captures correctly.

Turning `(a+)*` into `(a+)?` sounds good to me. We should probably think about some more cases though, e.g. does `(a*)+` turn into `(a*)?` as well? What about `((a+)*)*`? Would that have to be turned into `((a+)?)?`?

**Comment by keith-hall** [comment]
I also came across a regex with terrible performance:

`cargo run --example toy trace '(?:[^}\"\\]+(?:\\.)*)+(?="(?!"))' '[world], hello[test]);'`

in this case, it's a slightly different pattern, and I suspect we might need a solution whereby `fancy-regex` would "unroll the loop". (see https://github.com/trishume/syntect/pull/34#issuecomment-360067238)

**Comment by robinst** [comment]
@keith-hall I looked into this and the reason why this is fast in Oniguruma is that it has an optimization where it detects literals in the regex. In this example, it figures out that if the input doesn't contain `"`, it will never match. I've raised a pull request to document that, see above.

But if you change the input to `""test test test test test [world], hello[test]);`, it defeats the optimization and will be slow in Oniguruma too.

**Comment by robinst** [comment]
Closing this, as it's documented now and there will always be cases like these no matter what we do. So what we really need is a way to limit backtracking and aborting matching, see this issue: https://github.com/fancy-regex/fancy-regex/issues/6

We could optimize this specific case in the future but we don't need an open issue for that.
