### ISSUE TITLE
index out of bounds when referencing capture group before capturing it

### ISSUE THREAD

**Issue by TimNN** [google/fancy-regex#3]
The following causes a ``'byte index 18446744073709551615 is out of bounds of `a`'`` panic:

```rust
fn test() {
    Regex::new("\\1(.)").unwrap().is_match("a");
}
```

**Comment by robinst** [comment]
This issue has been fixed some time ago, `Regex::new` now returns an error with `InvalidBackref`.

(I don't have the permissions to close this issue.)

**Comment by davelab6** [comment]
Closing as fixed upstream
