### ISSUE TITLE
Bug in regex with lookaheads, wrong captures

### ISSUE THREAD

**Issue by SirVer** [google/fancy-regex#49]
This is with the latest release `0.1.0`.

This example yields wrong results. Python's `re` package gets it right with the same regex:

~~~rust
let r = fancy_regex::Regex::new(r"\s*(?<=[() ])(@\w+)(\([^)]*\))?\s*").unwrap();
let captures = r.captures(" @another(foo bar)   ").unwrap().unwrap();
assert_eq!(Some("@another"), captures.at(1));
assert_eq!(Some("(foo bar)"), captures.at(2));
~~~

The actual value of first group is ` @anothe` and the second is `r(foo bar`.

**Comment by SirVer** [comment]
Is it possible to change the google repositories readme with a warning that this crate has moved to a new location?

**Comment by raphlinus** [comment]
That's https://github.com/google/fancy-regex/pull/52 , which is waiting on action by someone at Google. I think I just need to find someone personally to ping.
