### ISSUE TITLE
Migrate development out of google organization

### ISSUE THREAD

**Issue by raphlinus** [google/fancy-regex#50]
Now that I've left Google, there's nobody there who's actively working on this. It's possible to transfer the repo, but the lightest weight process is to fork.

It makes sense for development to continue under my personal github account, but @robinst has been doing much more active development. In addition, I find my hands more than full with open source maintenance work these days. So if Robin wants it, I'd be happy to transfer effective ownership to him. Otherwise, I'll take it and do a minimal job as maintainer.

**Comment by robinst** [comment]
Hey! What do you think about creating a fancy-regex organization for the repository? I'd be happy to share maintainership.

**Comment by raphlinus** [comment]
That would also totally work. I'll get that rolling.

**Comment by robinst** [comment]
Yay! Would you mind making me an owner?

Also, looks like you forked the repository? That means it will always link back and compare it to the google repo, and code search doesn't work:

<img width="695" alt="screen shot 2018-10-03 at 15 49 45" src="https://user-images.githubusercontent.com/16778/46392266-28ad5b80-c724-11e8-8377-72070c71810d.png">

Not sure if you can unlink it in settings, or maybe we should instead just create a new repo and push all the branches/tags there. I can take care of that if you give me owner permissions.

**Comment by raphlinus** [comment]
Yes, you should be an owner now. I looked and don't think it's possible to unlink in settings. Feel free to migrate as you say, and lemme know if you want me to do anything else.

**Comment by robinst** [comment]
Thanks, I've created a support request now.

**Comment by robinst** [comment]
Repository is unlinked now :)!

**Comment by davelab6** [comment]
Closing
