### ISSUE TITLE
add a expand to Captures

### ISSUE THREAD

**Issue by Eh2406** [google/fancy-regex#9]
I am looking to use fancy-regex, but I don't see a replacement for [expand](https://docs.rs/regex/0.2.1/regex/struct.Captures.html#method.expand)? Am I missing something?

**Comment by davelab6** [comment]
Closing as this appears ancient.

**Comment by davelab6** [comment]
@Eh2406 See upstream https://github.com/fancy-regex/fancy-regex if you anything
